variables:
  DOCKER_DRIVER: overlay
  PKG_PATH: github.com/hprotzek/vault-unsealer
  GORELEASER_HASH: 634f5eedd1000a1eb675c2ca93bbbc889aa0388df76aea3501d7734616910584

stages:
- build
- deploy
- docker

# configure $GOPATH correctly on all build stages
before_script:
  - mkdir -p "${GOPATH}/src/${PKG_PATH}" && rmdir "${GOPATH}/src/${PKG_PATH}"
  - mv "${CI_PROJECT_DIR}" "${GOPATH}/src/${PKG_PATH}"
  - cd "${GOPATH}/src/${PKG_PATH}"
  - mkdir -p "${CI_PROJECT_DIR}"

after_script:
  - cd "/"
  - rm -rf "${CI_PROJECT_DIR}"
  - mv "${GOPATH}/src/${PKG_PATH}" "${CI_PROJECT_DIR}"

verify:golang:
  image: golang:1.9.2
  stage: build
  tags:
  - docker
  script:
  - make verify

build:golang:
  image: golang:1.9.2
  stage: build
  tags:
  - docker
  script:
  - make build
  except:
  - tags
  artifacts:
    paths:
    - vault-unsealer_linux_amd64

deploy:release:
  image: golang:1.9.2
  stage: deploy
  tags:
  - docker
  script:
  - umask 0077
  - mkdir -p /root/.gnupg
  - echo "${GPG_PRIVATE_KEY}" | base64 -d > /root/.gnupg/secring.gpg
  - curl -sL https://github.com/simonswine/goreleaser/releases/download/v0.36.0-gpg/goreleaser_Linux_x86_64.tar.gz > /tmp/goreleaser.tar.gz
  - echo "${GORELEASER_HASH}  /tmp/goreleaser.tar.gz" | sha256sum -c
  - cd /usr/local/bin && tar xvfz /tmp/goreleaser.tar.gz goreleaser
  - cd "${GOPATH}/src/${PKG_PATH}"
  - goreleaser
  - mv "dist/vault-unsealer_${CI_COMMIT_TAG}_linux_amd64/vault-unsealer_${CI_COMMIT_TAG}_linux_amd64" vault-unsealer_linux_amd64
  only:
  - tags
  artifacts:
    paths:
    - vault-unsealer_linux_amd64

docker:master_build_push:
  before_script: []
  after_script: []
  image: docker:1.12
  stage: docker
  tags:
  - docker
  services:
  - docker:dind
  script:
  - apk --update add make
  - mkdir -p ~/.docker && echo "${DOCKER_AUTH_CONFIG}" > ~/.docker/config.json && chmod 600 ~/.docker/config.json
  - make docker_push IMAGE_TAGS="${CI_BUILD_REF_SLUG}-${CI_PIPELINE_ID} canary"
  only:
  - master

docker:tags_build_push:
  before_script: []
  after_script: []
  image: docker:1.12
  stage: docker
  tags:
  - docker
  services:
  - docker:dind
  script:
  - apk --update add make
  - mkdir -p ~/.docker && echo "${DOCKER_AUTH_CONFIG}" > ~/.docker/config.json && chmod 600 ~/.docker/config.json
  - make docker_push IMAGE_TAGS="${CI_COMMIT_TAG} latest"
  only:
  - tags
